// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrmzdznniwqowqvybdvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZybXpkem5uaXdxb3dxdnliZHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzI2NTYsImV4cCI6MjA2NjU0ODY1Nn0.p0RjqiegmrUa7WP-ONSPrHDziLjug49qgN4lk9u8w6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);